import customtkinter

root=customtkinter.CTk()
root.geometry("400x330")
root.title("Calculator")
root.config(bg='black')

entryfield=customtkinter.CTkEntry(root,font=('arial',20,'bold'),text_color='white',fg_color='black',bg_color='black',border_color='white',width=380,height=50)
entryfield.grid(row=0,column=0,columnspan=4,padx=10,pady=10)

b7=customtkinter.CTkButton(root,font=('arial',20,'bold'),bg_color='black',text="7",cursor="hand2",width=80)
b7.grid(row=1,column=0,pady=10,padx=10)
b8=customtkinter.CTkButton(root,font=('arial',20,'bold'),bg_color='black',text="8",cursor="hand2",width=80)
b8.grid(row=1,column=1)
b9=customtkinter.CTkButton(root,font=('arial',20,'bold'),bg_color='black',text="9",cursor="hand2",width=80)
b9.grid(row=1,column=2)
badd=customtkinter.CTkButton(root,font=('arial',20,'bold'),bg_color='black',text="-",cursor="hand2",width=100,fg_color="orange",hover_color="orange3")
badd.grid(row=1,column=3)

b4=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="4",bg_color='black',cursor="hand2",width=80)
b4.grid(row=2,column=0,pady=10)
b5=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="5",bg_color='black',cursor="hand2",width=80)
b5.grid(row=2,column=1)
b6=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="6",bg_color='black',cursor="hand2",width=80)
b6.grid(row=2,column=2)
badd=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="+",bg_color='black',fg_color="orange",hover_color="orange3",cursor="hand2",width=100)
badd.grid(row=2,column=3)

b1=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="1",bg_color='black',cursor="hand2",width=80)
b1.grid(row=3,column=0,pady=10)
b2=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="2",bg_color='black',cursor="hand2",width=80)
b2.grid(row=3,column=1)
b3=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="3",bg_color='black',cursor="hand2",width=80)
b3.grid(row=3,column=2)
bmul=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="*",bg_color='black',fg_color="orange",hover_color="orange3",cursor="hand2",width=100)
bmul.grid(row=3,column=3)

b0=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="0",bg_color='black',cursor="hand2",width=80)
b0.grid(row=4,column=0,pady=10)
bdot=customtkinter.CTkButton(root,font=('arial',20,'bold'),text=".",bg_color='black',fg_color="orange",hover_color="orange3",cursor="hand2",width=80)
bdot.grid(row=4,column=1)
bdiv=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="/",bg_color='black',fg_color="orange",hover_color="orange3",cursor="hand2",width=80)
bdiv.grid(row=4,column=2)
bclear=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="C",bg_color='black',fg_color="red",hover_color="red3",cursor="hand2",width=100)
bclear.grid(row=4,column=3)

bequal=customtkinter.CTkButton(root,font=('arial',20,'bold'),text="=",bg_color='black',fg_color="green",hover_color="green3",cursor="hand2",width=380,height=40)
bequal.grid(row=5,column=0,columnspan=4,pady=10)
root.mainloop()